"""extend behavior profiles

Revision ID: 01a101271f56
Revises: 757db310ebf0
Create Date: 2026-07-16 03:37:44.402918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a101271f56'
down_revision: Union[str, Sequence[str], None] = '757db310ebf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_profiles', sa.Column('avg_login_hour', sa.Float(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('avg_failed_logins_per_day', sa.Float(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('known_ips', sa.JSON(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('known_devices', sa.JSON(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('risk_baseline', sa.Float(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('behavior_profiles', 'updated_at')
    op.drop_column('behavior_profiles', 'risk_baseline')
    op.drop_column('behavior_profiles', 'known_devices')
    op.drop_column('behavior_profiles', 'known_ips')
    op.drop_column('behavior_profiles', 'avg_failed_logins_per_day')
    op.drop_column('behavior_profiles', 'avg_login_hour')
    # ### end Alembic commands ###
