"""update risk assessment

Revision ID: 044084383816
Revises: 58cd79cc96ff
Create Date: 2026-07-13 03:11:02.502760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044084383816'
down_revision: Union[str, Sequence[str], None] = '58cd79cc96ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('risk_assessments', sa.Column('severity', sa.String(), nullable=False))
    op.drop_column('risk_assessments', 'reasons')
    op.drop_column('risk_assessments', 'risk_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_assessments', sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('risk_assessments', sa.Column('reasons', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('risk_assessments', 'severity')
    op.drop_column('risk_assessments', 'reason')
    # ### end Alembic commands ###
