"""update behavior profile

Revision ID: 58cd79cc96ff
Revises: 9b97bf7453df
Create Date: 2026-07-13 02:46:42.309044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58cd79cc96ff'
down_revision: Union[str, Sequence[str], None] = '9b97bf7453df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_profiles', sa.Column('login_count', sa.Integer(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('common_ip', sa.String(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('common_host', sa.String(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('first_seen', sa.DateTime(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('last_seen', sa.DateTime(), nullable=False))
    op.add_column('behavior_profiles', sa.Column('last_login', sa.DateTime(), nullable=False))
    op.drop_column('behavior_profiles', 'last_updated')
    op.drop_column('behavior_profiles', 'common_source_ip')
    op.drop_column('behavior_profiles', 'last_login_at')
    op.drop_column('behavior_profiles', 'avg_login_hour')
    op.drop_column('behavior_profiles', 'first_login_at')
    op.drop_column('behavior_profiles', 'total_logins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('behavior_profiles', sa.Column('total_logins', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('behavior_profiles', sa.Column('first_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('behavior_profiles', sa.Column('avg_login_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('behavior_profiles', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('behavior_profiles', sa.Column('common_source_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('behavior_profiles', sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('behavior_profiles', 'last_login')
    op.drop_column('behavior_profiles', 'last_seen')
    op.drop_column('behavior_profiles', 'first_seen')
    op.drop_column('behavior_profiles', 'common_host')
    op.drop_column('behavior_profiles', 'common_ip')
    op.drop_column('behavior_profiles', 'login_count')
    # ### end Alembic commands ###
