"""add evidences table

Revision ID: 74a1755b38df
Revises: 36e820feae5f
Create Date: 2026-07-12 03:28:44.085297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74a1755b38df'
down_revision: Union[str, Sequence[str], None] = '36e820feae5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_incident_id'), 'evidences', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidences_sha256_hash'), 'evidences', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_evidences_username'), 'evidences', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidences_username'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_sha256_hash'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_incident_id'), table_name='evidences')
    op.drop_table('evidences')
    # ### end Alembic commands ###
