"""add devices table

Revision ID: 757db310ebf0
Revises: 10670393cb69
Create Date: 2026-07-16 02:11:36.102576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '757db310ebf0'
down_revision: Union[str, Sequence[str], None] = '10670393cb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=150), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('owner_username', sa.String(length=100), nullable=True),
    sa.Column('agent_id', sa.String(length=150), nullable=True),
    sa.Column('collector_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_agent_id'), 'devices', ['agent_id'], unique=True)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_index(op.f('ix_devices_owner_username'), 'devices', ['owner_username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_owner_username'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_agent_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
