"""add incidents table

Revision ID: 8439bdcad57a
Revises: 45e3bf764b12
Create Date: 2026-07-13 04:10:16.917526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8439bdcad57a'
down_revision: Union[str, Sequence[str], None] = '45e3bf764b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('alert_id', sa.Integer(), nullable=False))
    op.add_column('incidents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('incidents', sa.Column('closed_at', sa.DateTime(), nullable=True))
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_incidents_risk_assessment_id'), table_name='incidents')
    op.create_index(op.f('ix_incidents_alert_id'), 'incidents', ['alert_id'], unique=False)
    op.drop_column('incidents', 'detected_at')
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'risk_assessment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('risk_assessment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('incidents', sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('incidents', sa.Column('detected_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_incidents_alert_id'), table_name='incidents')
    op.create_index(op.f('ix_incidents_risk_assessment_id'), 'incidents', ['risk_assessment_id'], unique=False)
    op.alter_column('incidents', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('incidents', 'closed_at')
    op.drop_column('incidents', 'created_at')
    op.drop_column('incidents', 'alert_id')
    # ### end Alembic commands ###
