"""restore incident and normalized event tables

Revision ID: 8c2e980a8211
Revises: 7928df093e9a
Create Date: 2026-07-19 07:51:55.280376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2e980a8211'
down_revision: Union[str, Sequence[str], None] = '7928df093e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_username'), 'alerts', ['username'], unique=False)
    op.create_table('behavior_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('common_ip', sa.String(length=100), nullable=False),
    sa.Column('common_host', sa.String(length=100), nullable=False),
    sa.Column('avg_login_hour', sa.Float(), nullable=False),
    sa.Column('avg_failed_logins_per_day', sa.Float(), nullable=False),
    sa.Column('known_ips', sa.JSON(), nullable=False),
    sa.Column('known_devices', sa.JSON(), nullable=False),
    sa.Column('risk_baseline', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_profiles_username'), 'behavior_profiles', ['username'], unique=True)
    op.create_table('blockchain_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_blocks_block_hash'), 'blockchain_blocks', ['block_hash'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_block_index'), 'blockchain_blocks', ['block_index'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_evidence_id'), 'blockchain_blocks', ['evidence_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=150), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('os_name', sa.String(length=150), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('owner_username', sa.String(length=100), nullable=True),
    sa.Column('agent_id', sa.String(length=150), nullable=True),
    sa.Column('collector_version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_agent_id'), 'devices', ['agent_id'], unique=True)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=True)
    op.create_index(op.f('ix_devices_mac_address'), 'devices', ['mac_address'], unique=True)
    op.create_index(op.f('ix_devices_owner_username'), 'devices', ['owner_username'], unique=False)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_incident_id'), 'evidences', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidences_sha256_hash'), 'evidences', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_evidences_username'), 'evidences', ['username'], unique=False)
    op.create_table('failed_login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sub_status', sa.String(), nullable=True),
    sa.Column('failed_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_login_events_id'), 'failed_login_events', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_alert_id'), 'incidents', ['alert_id'], unique=False)
    op.create_index(op.f('ix_incidents_username'), 'incidents', ['username'], unique=False)
    op.create_table('investigation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('mitre_techniques', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_reports_incident_id'), 'investigation_reports', ['incident_id'], unique=True)
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('source_ip', sa.String(length=100), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('normalized_windows_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('computer', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_windows_events_event_id'), 'normalized_windows_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_normalized_windows_events_raw_event_id'), 'normalized_windows_events', ['raw_event_id'], unique=False)
    op.create_table('raw_windows_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('computer', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('parsed_status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_windows_events_event_id'), 'raw_windows_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_raw_windows_events_record_id'), 'raw_windows_events', ['record_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_username'), 'risk_assessments', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('incident_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_events_incident_id'), 'incident_events', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_events_incident_id'), table_name='incident_events')
    op.drop_table('incident_events')
    op.drop_table('users')
    op.drop_index(op.f('ix_risk_assessments_username'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_raw_windows_events_record_id'), table_name='raw_windows_events')
    op.drop_index(op.f('ix_raw_windows_events_event_id'), table_name='raw_windows_events')
    op.drop_table('raw_windows_events')
    op.drop_index(op.f('ix_normalized_windows_events_raw_event_id'), table_name='normalized_windows_events')
    op.drop_index(op.f('ix_normalized_windows_events_event_id'), table_name='normalized_windows_events')
    op.drop_table('normalized_windows_events')
    op.drop_table('login_events')
    op.drop_index(op.f('ix_investigation_reports_incident_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    op.drop_index(op.f('ix_incidents_username'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_alert_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_failed_login_events_id'), table_name='failed_login_events')
    op.drop_table('failed_login_events')
    op.drop_index(op.f('ix_evidences_username'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_sha256_hash'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_incident_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_devices_owner_username'), table_name='devices')
    op.drop_index(op.f('ix_devices_mac_address'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_agent_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_blockchain_blocks_evidence_id'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_index'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_hash'), table_name='blockchain_blocks')
    op.drop_table('blockchain_blocks')
    op.drop_index(op.f('ix_behavior_profiles_username'), table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    op.drop_index(op.f('ix_alerts_username'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
