"""add investigation reports table

Revision ID: b737f2bd03ba
Revises: df49fc7d5385
Create Date: 2026-07-12 04:16:14.372211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b737f2bd03ba'
down_revision: Union[str, Sequence[str], None] = 'df49fc7d5385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('mitre_techniques', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_reports_incident_id'), 'investigation_reports', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investigation_reports_incident_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    # ### end Alembic commands ###
