"""add failed login events

Revision ID: c62ee4854805
Revises: ca25acb64e33
Create Date: 2026-07-13 02:08:34.373183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62ee4854805'
down_revision: Union[str, Sequence[str], None] = 'ca25acb64e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=False),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sub_status', sa.String(), nullable=True),
    sa.Column('failed_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_login_events_id'), 'failed_login_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_login_events_id'), table_name='failed_login_events')
    op.drop_table('failed_login_events')
    # ### end Alembic commands ###
