"""add raw windows events

Revision ID: ca25acb64e33
Revises: b737f2bd03ba
Create Date: 2026-07-13 01:47:44.528744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca25acb64e33'
down_revision: Union[str, Sequence[str], None] = 'b737f2bd03ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_blocks_block_hash'), 'blockchain_blocks', ['block_hash'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_block_index'), 'blockchain_blocks', ['block_index'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_evidence_id'), 'blockchain_blocks', ['evidence_id'], unique=True)
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_incident_id'), 'evidences', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidences_sha256_hash'), 'evidences', ['sha256_hash'], unique=True)
    op.create_index(op.f('ix_evidences_username'), 'evidences', ['username'], unique=False)
    op.create_table('investigation_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('mitre_techniques', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('prompt_snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_reports_incident_id'), 'investigation_reports', ['incident_id'], unique=True)
    op.create_table('raw_windows_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('computer', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('xml', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_windows_events_event_id'), 'raw_windows_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_raw_windows_events_record_id'), 'raw_windows_events', ['record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_windows_events_record_id'), table_name='raw_windows_events')
    op.drop_index(op.f('ix_raw_windows_events_event_id'), table_name='raw_windows_events')
    op.drop_table('raw_windows_events')
    op.drop_index(op.f('ix_investigation_reports_incident_id'), table_name='investigation_reports')
    op.drop_table('investigation_reports')
    op.drop_index(op.f('ix_evidences_username'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_sha256_hash'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_incident_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_blockchain_blocks_evidence_id'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_index'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_hash'), table_name='blockchain_blocks')
    op.drop_table('blockchain_blocks')
    # ### end Alembic commands ###
