"""add blockchain blocks table

Revision ID: df49fc7d5385
Revises: 74a1755b38df
Create Date: 2026-07-12 03:44:03.128655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df49fc7d5385'
down_revision: Union[str, Sequence[str], None] = '74a1755b38df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('evidence_hash', sa.String(length=64), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('block_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_blocks_block_hash'), 'blockchain_blocks', ['block_hash'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_block_index'), 'blockchain_blocks', ['block_index'], unique=True)
    op.create_index(op.f('ix_blockchain_blocks_evidence_id'), 'blockchain_blocks', ['evidence_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blockchain_blocks_evidence_id'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_index'), table_name='blockchain_blocks')
    op.drop_index(op.f('ix_blockchain_blocks_block_hash'), table_name='blockchain_blocks')
    op.drop_table('blockchain_blocks')
    # ### end Alembic commands ###
